---

  - name: "Install requirements for docker"
    ansible.builtin.apt:
      name: "{{ item }}"
      state: "latest"
    with_items:
      - ca-certificates
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release
      - itop

  - name: apt update
    apt:
      update_cache: yes

  - name: add docker apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: install docker and it's dependencies
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present

  - name: start and enable docker daemon
    service:
      name: docker
      state: started
      enabled: yes